// ISO 4217 Currency Codes (All 180+ official fiat currencies)
// Plus major cryptocurrencies and stablecoins
export const CURRENCIES = [
  // Major Fiat Currencies
  { code: 'USD', name: 'US Dollar', symbol: '$', type: 'fiat' },
  { code: 'EUR', name: 'Euro', symbol: '€', type: 'fiat' },
  { code: 'GBP', name: 'British Pound', symbol: '£', type: 'fiat' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', type: 'fiat' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', type: 'fiat' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', type: 'fiat' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', type: 'fiat' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', type: 'fiat' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', type: 'fiat' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', type: 'fiat' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', type: 'fiat' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', type: 'fiat' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', type: 'fiat' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', type: 'fiat' },
  { code: 'MXN', name: 'Mexican Peso', symbol: 'MX$', type: 'fiat' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', type: 'fiat' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', type: 'fiat' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', type: 'fiat' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', type: 'fiat' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', type: 'fiat' },
  
  // Middle East & Africa
  { code: 'AED', name: 'UAE Dirham', symbol: 'AED', type: 'fiat' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: 'SAR', type: 'fiat' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'QAR', type: 'fiat' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KWD', type: 'fiat' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: 'BHD', type: 'fiat' },
  { code: 'OMR', name: 'Omani Rial', symbol: 'OMR', type: 'fiat' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'JOD', type: 'fiat' },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'L£', type: 'fiat' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', type: 'fiat' },
  { code: 'ILS', name: 'Israeli Shekel', symbol: '₪', type: 'fiat' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'MAD', type: 'fiat' },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'TND', type: 'fiat' },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'DZD', type: 'fiat' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', type: 'fiat' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', type: 'fiat' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GH₵', type: 'fiat' },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', type: 'fiat' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', type: 'fiat' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', type: 'fiat' },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', type: 'fiat' },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', type: 'fiat' },
  
  // Asia-Pacific
  { code: 'THB', name: 'Thai Baht', symbol: '฿', type: 'fiat' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', type: 'fiat' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', type: 'fiat' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', type: 'fiat' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', type: 'fiat' },
  { code: 'TWD', name: 'Taiwan Dollar', symbol: 'NT$', type: 'fiat' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', type: 'fiat' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', type: 'fiat' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', type: 'fiat' },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: 'Rs', type: 'fiat' },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', type: 'fiat' },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', type: 'fiat' },
  { code: 'LAK', name: 'Lao Kip', symbol: '₭', type: 'fiat' },
  { code: 'BND', name: 'Brunei Dollar', symbol: 'B$', type: 'fiat' },
  { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP$', type: 'fiat' },
  { code: 'FJD', name: 'Fijian Dollar', symbol: 'FJ$', type: 'fiat' },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', type: 'fiat' },
  
  // Europe (Non-Euro)
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', type: 'fiat' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', type: 'fiat' },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', type: 'fiat' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', type: 'fiat' },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', type: 'fiat' },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', type: 'fiat' },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', type: 'fiat' },
  { code: 'ISK', name: 'Icelandic Krona', symbol: 'kr', type: 'fiat' },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'din', type: 'fiat' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', type: 'fiat' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Mark', symbol: 'KM', type: 'fiat' },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', type: 'fiat' },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'L', type: 'fiat' },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', type: 'fiat' },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', type: 'fiat' },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏', type: 'fiat' },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', type: 'fiat' },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', type: 'fiat' },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', type: 'fiat' },
  { code: 'UZS', name: 'Uzbekistani Som', symbol: 'soʻm', type: 'fiat' },
  
  // Americas
  { code: 'ARS', name: 'Argentine Peso', symbol: 'ARS', type: 'fiat' },
  { code: 'CLP', name: 'Chilean Peso', symbol: 'CLP', type: 'fiat' },
  { code: 'COP', name: 'Colombian Peso', symbol: 'COP', type: 'fiat' },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', type: 'fiat' },
  { code: 'VES', name: 'Venezuelan Bolívar', symbol: 'Bs', type: 'fiat' },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', type: 'fiat' },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs', type: 'fiat' },
  { code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲', type: 'fiat' },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', type: 'fiat' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', type: 'fiat' },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', type: 'fiat' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', type: 'fiat' },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', type: 'fiat' },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', type: 'fiat' },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', type: 'fiat' },
  { code: 'TTD', name: 'Trinidad & Tobago Dollar', symbol: 'TT$', type: 'fiat' },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: 'Bds$', type: 'fiat' },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: 'B$', type: 'fiat' },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: 'EC$', type: 'fiat' },
  { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', type: 'fiat' },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', type: 'fiat' },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', type: 'fiat' },
  { code: 'CUP', name: 'Cuban Peso', symbol: '₱', type: 'fiat' },
  
  // Pacific Islands
  { code: 'WST', name: 'Samoan Tala', symbol: 'WS$', type: 'fiat' },
  { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', type: 'fiat' },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', type: 'fiat' },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SI$', type: 'fiat' },
  
  // Additional Asian Currencies
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', type: 'fiat' },
  { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'с', type: 'fiat' },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'ЅМ', type: 'fiat' },
  { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'm', type: 'fiat' },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', type: 'fiat' },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', type: 'fiat' },
  { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', type: 'fiat' },
  { code: 'SYP', name: 'Syrian Pound', symbol: '£S', type: 'fiat' },
  { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', type: 'fiat' },
  
  // Additional African Currencies
  { code: 'BWP', name: 'Botswanan Pula', symbol: 'P', type: 'fiat' },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', type: 'fiat' },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', type: 'fiat' },
  { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'E', type: 'fiat' },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'L', type: 'fiat' },
  { code: 'NAD', name: 'Namibian Dollar', symbol: 'N$', type: 'fiat' },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', type: 'fiat' },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', type: 'fiat' },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', type: 'fiat' },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'RF', type: 'fiat' },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', type: 'fiat' },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', type: 'fiat' },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', type: 'fiat' },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'Sh', type: 'fiat' },
  { code: 'SDG', name: 'Sudanese Pound', symbol: '£SD', type: 'fiat' },
  { code: 'SSP', name: 'South Sudanese Pound', symbol: '£', type: 'fiat' },
  { code: 'LRD', name: 'Liberian Dollar', symbol: 'L$', type: 'fiat' },
  { code: 'SLE', name: 'Sierra Leonean Leone', symbol: 'Le', type: 'fiat' },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', type: 'fiat' },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', type: 'fiat' },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$', type: 'fiat' },
  { code: 'STN', name: 'São Tomé & Príncipe Dobra', symbol: 'Db', type: 'fiat' },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', type: 'fiat' },
  { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA', type: 'fiat' },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA', type: 'fiat' },
  
  // Special & Regional Currencies
  { code: 'XPF', name: 'CFP Franc (Pacific)', symbol: '₣', type: 'fiat' },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£', type: 'fiat' },
  { code: 'GIP', name: 'Gibraltar Pound', symbol: '£', type: 'fiat' },
  { code: 'SHP', name: 'Saint Helena Pound', symbol: '£', type: 'fiat' },
  
  // Major Cryptocurrencies
  { code: 'BTC', name: 'Bitcoin', symbol: '₿', type: 'crypto' },
  { code: 'ETH', name: 'Ethereum', symbol: 'Ξ', type: 'crypto' },
  { code: 'BNB', name: 'Binance Coin', symbol: 'BNB', type: 'crypto' },
  { code: 'XRP', name: 'Ripple', symbol: 'XRP', type: 'crypto' },
  { code: 'ADA', name: 'Cardano', symbol: 'ADA', type: 'crypto' },
  { code: 'SOL', name: 'Solana', symbol: 'SOL', type: 'crypto' },
  { code: 'DOT', name: 'Polkadot', symbol: 'DOT', type: 'crypto' },
  { code: 'DOGE', name: 'Dogecoin', symbol: 'Ð', type: 'crypto' },
  { code: 'MATIC', name: 'Polygon', symbol: 'MATIC', type: 'crypto' },
  { code: 'AVAX', name: 'Avalanche', symbol: 'AVAX', type: 'crypto' },
  { code: 'LINK', name: 'Chainlink', symbol: 'LINK', type: 'crypto' },
  { code: 'UNI', name: 'Uniswap', symbol: 'UNI', type: 'crypto' },
  { code: 'LTC', name: 'Litecoin', symbol: 'Ł', type: 'crypto' },
  { code: 'BCH', name: 'Bitcoin Cash', symbol: 'BCH', type: 'crypto' },
  { code: 'ATOM', name: 'Cosmos', symbol: 'ATOM', type: 'crypto' },
  { code: 'XLM', name: 'Stellar', symbol: 'XLM', type: 'crypto' },
  { code: 'ALGO', name: 'Algorand', symbol: 'ALGO', type: 'crypto' },
  { code: 'VET', name: 'VeChain', symbol: 'VET', type: 'crypto' },
  { code: 'XMR', name: 'Monero', symbol: 'XMR', type: 'crypto' },
  { code: 'FIL', name: 'Filecoin', symbol: 'FIL', type: 'crypto' },
  { code: 'TRX', name: 'TRON', symbol: 'TRX', type: 'crypto' },
  { code: 'ETC', name: 'Ethereum Classic', symbol: 'ETC', type: 'crypto' },
  { code: 'NEAR', name: 'NEAR Protocol', symbol: 'NEAR', type: 'crypto' },
  { code: 'APT', name: 'Aptos', symbol: 'APT', type: 'crypto' },
  { code: 'ARB', name: 'Arbitrum', symbol: 'ARB', type: 'crypto' },
  { code: 'OP', name: 'Optimism', symbol: 'OP', type: 'crypto' },
  { code: 'ICP', name: 'Internet Computer', symbol: 'ICP', type: 'crypto' },
  { code: 'HBAR', name: 'Hedera', symbol: 'HBAR', type: 'crypto' },
  { code: 'SUI', name: 'Sui', symbol: 'SUI', type: 'crypto' },
  { code: 'TON', name: 'Toncoin', symbol: 'TON', type: 'crypto' },
  
  // Stablecoins
  { code: 'USDT', name: 'Tether', symbol: 'USDT', type: 'stablecoin' },
  { code: 'USDC', name: 'USD Coin', symbol: 'USDC', type: 'stablecoin' },
  { code: 'BUSD', name: 'Binance USD', symbol: 'BUSD', type: 'stablecoin' },
  { code: 'DAI', name: 'Dai', symbol: 'DAI', type: 'stablecoin' },
  { code: 'TUSD', name: 'TrueUSD', symbol: 'TUSD', type: 'stablecoin' },
  { code: 'USDP', name: 'Pax Dollar', symbol: 'USDP', type: 'stablecoin' },
  { code: 'GUSD', name: 'Gemini Dollar', symbol: 'GUSD', type: 'stablecoin' },
  { code: 'FRAX', name: 'Frax', symbol: 'FRAX', type: 'stablecoin' },
  { code: 'USDD', name: 'USDD', symbol: 'USDD', type: 'stablecoin' },
  { code: 'PYUSD', name: 'PayPal USD', symbol: 'PYUSD', type: 'stablecoin' },
  { code: 'FDUSD', name: 'First Digital USD', symbol: 'FDUSD', type: 'stablecoin' },
  { code: 'EURT', name: 'Tether EUR', symbol: 'EUR₮', type: 'stablecoin' },
  { code: 'EURC', name: 'Euro Coin', symbol: 'EURC', type: 'stablecoin' }
];

// Tax types by country (ISO standards: VAT Directive 2006/112/EC, OECD standards)
export const TAX_RULES_BY_COUNTRY = [
  // Europe - VAT (EU VAT Directive)
  { code: 'AT', tax_type: 'VAT', rate: 20, reverse_charge: true },
  { code: 'BE', tax_type: 'VAT', rate: 21, reverse_charge: true },
  { code: 'BG', tax_type: 'VAT', rate: 20, reverse_charge: true },
  { code: 'HR', tax_type: 'VAT', rate: 25, reverse_charge: true },
  { code: 'CY', tax_type: 'VAT', rate: 19, reverse_charge: true },
  { code: 'CZ', tax_type: 'VAT', rate: 21, reverse_charge: true },
  { code: 'DK', tax_type: 'VAT', rate: 25, reverse_charge: true },
  { code: 'EE', tax_type: 'VAT', rate: 20, reverse_charge: true },
  { code: 'FI', tax_type: 'VAT', rate: 24, reverse_charge: true },
  { code: 'FR', tax_type: 'VAT', rate: 20, reverse_charge: true },
  { code: 'DE', tax_type: 'VAT', rate: 19, reverse_charge: true },
  { code: 'GR', tax_type: 'VAT', rate: 24, reverse_charge: true },
  { code: 'HU', tax_type: 'VAT', rate: 27, reverse_charge: true },
  { code: 'IE', tax_type: 'VAT', rate: 23, reverse_charge: true },
  { code: 'IT', tax_type: 'VAT', rate: 22, reverse_charge: true },
  { code: 'LV', tax_type: 'VAT', rate: 21, reverse_charge: true },
  { code: 'LT', tax_type: 'VAT', rate: 21, reverse_charge: true },
  { code: 'LU', tax_type: 'VAT', rate: 17, reverse_charge: true },
  { code: 'MT', tax_type: 'VAT', rate: 18, reverse_charge: true },
  { code: 'NL', tax_type: 'VAT', rate: 21, reverse_charge: true },
  { code: 'PL', tax_type: 'VAT', rate: 23, reverse_charge: true },
  { code: 'PT', tax_type: 'VAT', rate: 23, reverse_charge: true },
  { code: 'RO', tax_type: 'VAT', rate: 19, reverse_charge: true },
  { code: 'SK', tax_type: 'VAT', rate: 20, reverse_charge: true },
  { code: 'SI', tax_type: 'VAT', rate: 22, reverse_charge: true },
  { code: 'ES', tax_type: 'VAT', rate: 21, reverse_charge: true },
  { code: 'SE', tax_type: 'VAT', rate: 25, reverse_charge: true },
  { code: 'GB', tax_type: 'VAT', rate: 20, reverse_charge: true },
  { code: 'NO', tax_type: 'VAT', rate: 25, reverse_charge: false },
  { code: 'CH', tax_type: 'VAT', rate: 7.7, reverse_charge: false },
  
  // Asia-Pacific - GST/VAT
  { code: 'AU', tax_type: 'GST', rate: 10, reverse_charge: false },
  { code: 'NZ', tax_type: 'GST', rate: 15, reverse_charge: false },
  { code: 'SG', tax_type: 'GST', rate: 9, reverse_charge: false },
  { code: 'MY', tax_type: 'SST', rate: 6, reverse_charge: false },
  { code: 'IN', tax_type: 'GST', rate: 18, reverse_charge: false },
  { code: 'ID', tax_type: 'VAT', rate: 11, reverse_charge: false },
  { code: 'PH', tax_type: 'VAT', rate: 12, reverse_charge: false },
  { code: 'TH', tax_type: 'VAT', rate: 7, reverse_charge: false },
  { code: 'VN', tax_type: 'VAT', rate: 10, reverse_charge: false },
  { code: 'JP', tax_type: 'Consumption Tax', rate: 10, reverse_charge: false },
  { code: 'KR', tax_type: 'VAT', rate: 10, reverse_charge: false },
  { code: 'CN', tax_type: 'VAT', rate: 13, reverse_charge: false },
  { code: 'TW', tax_type: 'VAT', rate: 5, reverse_charge: false },
  { code: 'HK', tax_type: 'None', rate: 0, reverse_charge: false },
  { code: 'PK', tax_type: 'Sales Tax', rate: 17, reverse_charge: false },
  { code: 'BD', tax_type: 'VAT', rate: 15, reverse_charge: false },
  { code: 'LK', tax_type: 'VAT', rate: 15, reverse_charge: false },
  
  // Middle East
  { code: 'AE', tax_type: 'VAT', rate: 5, reverse_charge: false },
  { code: 'SA', tax_type: 'VAT', rate: 15, reverse_charge: false },
  { code: 'BH', tax_type: 'VAT', rate: 10, reverse_charge: false },
  { code: 'OM', tax_type: 'VAT', rate: 5, reverse_charge: false },
  { code: 'QA', tax_type: 'None', rate: 0, reverse_charge: false },
  { code: 'KW', tax_type: 'None', rate: 0, reverse_charge: false },
  { code: 'IL', tax_type: 'VAT', rate: 17, reverse_charge: false },
  { code: 'TR', tax_type: 'VAT', rate: 20, reverse_charge: false },
  { code: 'EG', tax_type: 'VAT', rate: 14, reverse_charge: false },
  
  // Americas
  { code: 'US', tax_type: 'Sales Tax', rate: 0, reverse_charge: false },
  { code: 'CA', tax_type: 'GST/HST', rate: 5, reverse_charge: false },
  { code: 'MX', tax_type: 'IVA', rate: 16, reverse_charge: false },
  { code: 'BR', tax_type: 'IVA', rate: 17, reverse_charge: false },
  { code: 'CL', tax_type: 'IVA', rate: 19, reverse_charge: false },
  { code: 'CO', tax_type: 'IVA', rate: 19, reverse_charge: false },
  { code: 'AR', tax_type: 'IVA', rate: 21, reverse_charge: false },
  { code: 'PE', tax_type: 'IGV', rate: 18, reverse_charge: false },
  { code: 'UY', tax_type: 'IVA', rate: 22, reverse_charge: false },
  
  // Africa
  { code: 'ZA', tax_type: 'VAT', rate: 15, reverse_charge: false },
  { code: 'NG', tax_type: 'VAT', rate: 7.5, reverse_charge: false },
  { code: 'KE', tax_type: 'VAT', rate: 16, reverse_charge: false },
  { code: 'GH', tax_type: 'VAT', rate: 12.5, reverse_charge: false },
  { code: 'ET', tax_type: 'VAT', rate: 15, reverse_charge: false },
  { code: 'TZ', tax_type: 'VAT', rate: 18, reverse_charge: false },
  { code: 'UG', tax_type: 'VAT', rate: 18, reverse_charge: false },
  { code: 'RW', tax_type: 'VAT', rate: 18, reverse_charge: false },
  { code: 'MA', tax_type: 'VAT', rate: 20, reverse_charge: false },
  { code: 'TN', tax_type: 'VAT', rate: 19, reverse_charge: false }
];

export function getCurrencySymbol(code) {
  return CURRENCIES.find(c => c.code === code)?.symbol || code;
}

export function getCurrencyName(code) {
  return CURRENCIES.find(c => c.code === code)?.name || code;
}

export function getTaxRule(countryCode) {
  return TAX_RULES_BY_COUNTRY.find(t => t.code === countryCode);
}

export function getCurrenciesByType(type) {
  if (!type) return CURRENCIES;
  return CURRENCIES.filter(c => c.type === type);
}