// Comprehensive global mapping of ISO 3166-1 country codes to official business registries
export const COUNTRY_REGISTRY_MAP = {
  // Africa
  'DZ': [{ code: 'DZ-RCS', name: 'Registre du Commerce et du Timbre' }],
  'AO': [{ code: 'AO-IRJ', name: 'Instituto de Registro de Propriedade Intelectual' }],
  'BJ': [{ code: 'BJ-RCC', name: 'Registre du Commerce et du Crédit' }],
  'BW': [{ code: 'BW-CR', name: 'Companies and Intellectual Property Authority (CIPA)' }],
  'BF': [{ code: 'BF-RCC', name: 'Registre du Commerce et du Crédit' }],
  'BI': [{ code: 'BI-RCC', name: 'Registre du Commerce et du Crédit' }],
  'CM': [{ code: 'CM-RCC', name: 'Registre du Commerce et du Crédit' }],
  'CV': [{ code: 'CV-CR', name: 'Conservatória de Registo Comercial' }],
  'CF': [{ code: 'CF-RCC', name: 'Registre du Commerce et du Crédit' }],
  'TD': [{ code: 'TD-RCC', name: 'Registre du Commerce et du Crédit' }],
  'KM': [{ code: 'KM-RCC', name: 'Registre du Commerce et du Crédit' }],
  'CG': [{ code: 'CG-RCC', name: 'Registre du Commerce et du Crédit' }],
  'CD': [{ code: 'CD-RCC', name: 'Registre du Commerce et du Crédit' }],
  'CI': [{ code: 'CI-RCC', name: 'Registre du Commerce et du Crédit' }],
  'DJ': [{ code: 'DJ-RCC', name: 'Registre du Commerce et du Crédit' }],
  'EG': [{ code: 'EG-CRA', name: 'Central Agency for Public Mobilization and Statistics' }],
  'GQ': [{ code: 'GQ-RCC', name: 'Registre du Commerce et du Crédit' }],
  'ER': [{ code: 'ER-MoT', name: 'Ministry of Trade' }],
  'ET': [{ code: 'ET-FTRA', name: 'Federal Trade and Industry Bureau' }],
  'GA': [{ code: 'GA-RCC', name: 'Registre du Commerce et du Crédit' }],
  'GM': [{ code: 'GM-BR', name: 'Business Registration' }],
  'GH': [{ code: 'GH-RSD', name: 'Registrar of Companies' }],
  'GN': [{ code: 'GN-RCC', name: 'Registre du Commerce et du Crédit' }],
  'GW': [{ code: 'GW-RCC', name: 'Conservatória de Registo Comercial' }],
  'KE': [{ code: 'KE-ROC', name: 'Registrar of Companies' }],
  'LS': [{ code: 'LS-CR', name: 'Companies House' }],
  'LR': [{ code: 'LR-MoC', name: 'Ministry of Commerce' }],
  'LY': [{ code: 'LY-RCC', name: 'Registre du Commerce et du Crédit' }],
  'MG': [{ code: 'MG-RCC', name: 'Registre du Commerce et du Crédit' }],
  'MW': [{ code: 'MW-BR', name: 'Business Registrar' }],
  'ML': [{ code: 'ML-RCC', name: 'Registre du Commerce et du Crédit' }],
  'MR': [{ code: 'MR-RCC', name: 'Registre du Commerce et du Crédit' }],
  'MU': [{ code: 'MU-ROC', name: 'Registrar of Companies' }],
  'MA': [{ code: 'MA-RCC', name: 'Centre Régional d\'Investissement' }],
  'MZ': [{ code: 'MZ-IRJ', name: 'Instituto de Registo de Propriedade Intelectual' }],
  'NA': [{ code: 'NA-CR', name: 'Companies and Intellectual Property Authority' }],
  'NE': [{ code: 'NE-RCC', name: 'Registre du Commerce et du Crédit' }],
  'NG': [{ code: 'NG-CAC', name: 'Corporate Affairs Commission' }],
  'RW': [{ code: 'RW-RCC', name: 'Registre du Commerce et du Crédit' }],
  'ST': [{ code: 'ST-CR', name: 'Conservatória de Registo Comercial' }],
  'SN': [{ code: 'SN-RCC', name: 'Registre du Commerce et du Crédit' }],
  'SC': [{ code: 'SC-ROC', name: 'Registrar of Companies' }],
  'SL': [{ code: 'SL-CR', name: 'Corporate Affairs Division' }],
  'SO': [{ code: 'SO-MoC', name: 'Ministry of Commerce' }],
  'ZA': [{ code: 'ZA-CIPC', name: 'Companies and Intellectual Property Commission' }],
  'SS': [{ code: 'SS-MoC', name: 'Ministry of Commerce' }],
  'SD': [{ code: 'SD-RCC', name: 'Business Registry' }],
  'SZ': [{ code: 'SZ-CR', name: 'Companies House' }],
  'TZ': [{ code: 'TZ-ROC', name: 'Registrar of Companies' }],
  'TG': [{ code: 'TG-RCC', name: 'Registre du Commerce et du Crédit' }],
  'TN': [{ code: 'TN-RCC', name: 'Registre du Commerce et du Crédit' }],
  'UG': [{ code: 'UG-ROC', name: 'Registrar of Companies' }],
  'ZM': [{ code: 'ZM-PAC', name: 'Patents and Companies Registration Office' }],
  'ZW': [{ code: 'ZW-PAC', name: 'Patents and Companies Registration Office' }],

  // Americas
  'AG': [{ code: 'AG-ROC', name: 'Registrar of Companies' }],
  'AR': [
    { code: 'AR-AFIP', name: 'Administración Federal de Ingresos Públicos' },
    { code: 'AR-IPP', name: 'Inspección de Personas Jurídicas' },
  ],
  'BS': [{ code: 'BS-RCC', name: 'Registrar of Companies and Intellectual Property' }],
  'BB': [{ code: 'BB-RCC', name: 'Companies House' }],
  'BZ': [{ code: 'BZ-RCC', name: 'Registrar of Companies' }],
  'BO': [{ code: 'BO-RPC', name: 'Registro de Comercio' }],
  'BR': [
    { code: 'BR-CNPJ', name: 'Cadastro Nacional da Pessoa Jurídica' },
    { code: 'BR-JUCERJA', name: 'Junta Comercial' },
  ],
  'CA': [
    { code: 'CA-IC', name: 'Corporations Canada (Federal)' },
    { code: 'CA-AB', name: 'Corporate Registry Alberta' },
    { code: 'CA-BC', name: 'BC Registry Services' },
    { code: 'CA-MB', name: 'Corporations Branch Manitoba' },
    { code: 'CA-NB', name: 'Companies and Cooperatives Division' },
    { code: 'CA-NL', name: 'Service NL - Registries Division' },
    { code: 'CA-NS', name: 'Service Nova Scotia and Municipal Relations' },
    { code: 'CA-NT', name: 'Business Registries Northwest Territories' },
    { code: 'CA-NU', name: 'Nunavut Registry' },
    { code: 'CA-ON', name: 'Ontario Business Registry' },
    { code: 'CA-PE', name: 'Corporate Services Prince Edward Island' },
    { code: 'CA-QC', name: 'Registraire des Entreprises Quebec' },
    { code: 'CA-SK', name: 'Companies Office Saskatchewan' },
    { code: 'CA-YT', name: 'Yukon Registry' },
  ],
  'CL': [
    { code: 'CL-SII', name: 'Servicio de Impuestos Internos' },
    { code: 'CL-CRC', name: 'Conservador de Bienes Raíces' },
  ],
  'CO': [{ code: 'CO-RMC', name: 'Registro Mercantil' }],
  'CR': [{ code: 'CR-PJ', name: 'Registro de Personas Jurídicas' }],
  'CU': [{ code: 'CU-RC', name: 'Registro de Comercio' }],
  'DM': [{ code: 'DM-ROC', name: 'Registrar of Companies' }],
  'DO': [{ code: 'DO-JCM', name: 'Junta de Comercio y Mercadería' }],
  'EC': [{ code: 'EC-SRI', name: 'Servicio de Rentas Internas' }],
  'SV': [{ code: 'SV-RMC', name: 'Registro de Comercio' }],
  'GD': [{ code: 'GD-ROC', name: 'Registrar of Companies' }],
  'GT': [{ code: 'GT-RMC', name: 'Registro Mercantil' }],
  'GY': [{ code: 'GY-ROC', name: 'Registrar of Companies' }],
  'HT': [{ code: 'HT-RCS', name: 'Bureau du Greffe du Commerce' }],
  'HN': [{ code: 'HN-RMC', name: 'Registro Mercantil' }],
  'JM': [{ code: 'JM-ROC', name: 'Registrar of Companies' }],
  'MX': [{ code: 'MX-RPC', name: 'Registro Público de Comercio' }],
  'NI': [{ code: 'NI-RMC', name: 'Registro Mercantil' }],
  'PA': [{ code: 'PA-RPC', name: 'Registro Público de Panamá' }],
  'PY': [{ code: 'PY-RPC', name: 'Registro Público de Comercio' }],
  'PE': [{ code: 'PE-SUNARP', name: 'Superintendencia Nacional de los Registros Públicos' }],
  'KN': [{ code: 'KN-ROC', name: 'Registrar of Companies' }],
  'LC': [{ code: 'LC-ROC', name: 'Registrar of Companies' }],
  'VC': [{ code: 'VC-ROC', name: 'Registrar of Companies' }],
  'SR': [{ code: 'SR-ROC', name: 'Registrar of Companies' }],
  'TT': [{ code: 'TT-ROC', name: 'Registrar of Companies' }],
  'US': [
    { code: 'US-FTC', name: 'Federal Trade Commission' },
    { code: 'US-AL', name: 'Secretary of State - Alabama' },
    { code: 'US-AK', name: 'Secretary of State - Alaska' },
    { code: 'US-AZ', name: 'Corporation Commission - Arizona' },
    { code: 'US-AR', name: 'Secretary of State - Arkansas' },
    { code: 'US-CA', name: 'Secretary of State - California' },
    { code: 'US-CO', name: 'Secretary of State - Colorado' },
    { code: 'US-CT', name: 'Secretary of State - Connecticut' },
    { code: 'US-DE', name: 'Division of Corporations - Delaware' },
    { code: 'US-FL', name: 'Secretary of State - Florida' },
    { code: 'US-GA', name: 'Secretary of State - Georgia' },
    { code: 'US-HI', name: 'Department of Commerce and Consumer Affairs - Hawaii' },
    { code: 'US-ID', name: 'Secretary of State - Idaho' },
    { code: 'US-IL', name: 'Secretary of State - Illinois' },
    { code: 'US-IN', name: 'Secretary of State - Indiana' },
    { code: 'US-IA', name: 'Secretary of State - Iowa' },
    { code: 'US-KS', name: 'Secretary of State - Kansas' },
    { code: 'US-KY', name: 'Secretary of State - Kentucky' },
    { code: 'US-LA', name: 'Secretary of State - Louisiana' },
    { code: 'US-ME', name: 'Secretary of State - Maine' },
    { code: 'US-MD', name: 'State Department of Assessments and Taxation - Maryland' },
    { code: 'US-MA', name: 'Secretary of State - Massachusetts' },
    { code: 'US-MI', name: 'Department of Licensing and Regulatory Affairs - Michigan' },
    { code: 'US-MN', name: 'Secretary of State - Minnesota' },
    { code: 'US-MS', name: 'Secretary of State - Mississippi' },
    { code: 'US-MO', name: 'Secretary of State - Missouri' },
    { code: 'US-MT', name: 'Secretary of State - Montana' },
    { code: 'US-NE', name: 'Secretary of State - Nebraska' },
    { code: 'US-NV', name: 'Secretary of State - Nevada' },
    { code: 'US-NH', name: 'Secretary of State - New Hampshire' },
    { code: 'US-NJ', name: 'Secretary of State - New Jersey' },
    { code: 'US-NM', name: 'Public Regulation Commission - New Mexico' },
    { code: 'US-NY', name: 'Department of State - New York' },
    { code: 'US-NC', name: 'Secretary of State - North Carolina' },
    { code: 'US-ND', name: 'Secretary of State - North Dakota' },
    { code: 'US-OH', name: 'Secretary of State - Ohio' },
    { code: 'US-OK', name: 'Secretary of State - Oklahoma' },
    { code: 'US-OR', name: 'Secretary of State - Oregon' },
    { code: 'US-PA', name: 'Department of State - Pennsylvania' },
    { code: 'US-RI', name: 'Secretary of State - Rhode Island' },
    { code: 'US-SC', name: 'Secretary of State - South Carolina' },
    { code: 'US-SD', name: 'Secretary of State - South Dakota' },
    { code: 'US-TN', name: 'Secretary of State - Tennessee' },
    { code: 'US-TX', name: 'Secretary of State - Texas' },
    { code: 'US-UT', name: 'Division of Corporations and Commercial Code - Utah' },
    { code: 'US-VT', name: 'Secretary of State - Vermont' },
    { code: 'US-VA', name: 'Clerk of Commission of the Virginia State Corporation Commission' },
    { code: 'US-WA', name: 'Secretary of State - Washington' },
    { code: 'US-WV', name: 'Secretary of State - West Virginia' },
    { code: 'US-WI', name: 'Secretary of State - Wisconsin' },
    { code: 'US-WY', name: 'Secretary of State - Wyoming' },
  ],
  'UY': [{ code: 'UY-DGI', name: 'Dirección General Impositiva' }],
  'VE': [{ code: 'VE-RMC', name: 'Registro Mercantil' }],

  // Asia
  'AF': [{ code: 'AF-MoC', name: 'Ministry of Commerce' }],
  'AM': [{ code: 'AM-SR', name: 'State Register' }],
  'AZ': [{ code: 'AZ-DSMSC', name: 'Department of State Services on Multiple Sources of Income' }],
  'BH': [{ code: 'BH-CR', name: 'Commercial Register' }],
  'BD': [{ code: 'BD-ROC', name: 'Registrar of Companies' }],
  'BT': [{ code: 'BT-DRC', name: 'Department of Revenue and Customs' }],
  'BN': [{ code: 'BN-MoL', name: 'Ministry of Law' }],
  'KH': [{ code: 'KH-MoC', name: 'Ministry of Commerce' }],
  'CN': [
    { code: 'CN-SAMR', name: 'State Administration for Market Regulation' },
    { code: 'CN-AAC', name: 'Administration of Industry and Commerce' },
  ],
  'GE': [{ code: 'GE-SR', name: 'State Register' }],
  'HK': [{ code: 'HK-CR', name: 'Companies Registry' }],
  'IN': [
    { code: 'IN-MCA', name: 'Ministry of Corporate Affairs - Registrar of Companies (Central)' },
    { code: 'IN-ROC-CHENNAI', name: 'Registrar of Companies - Chennai' },
    { code: 'IN-ROC-DELHI', name: 'Registrar of Companies - Delhi' },
    { code: 'IN-ROC-MUMBAI', name: 'Registrar of Companies - Mumbai' },
    { code: 'IN-ROC-KOLKATA', name: 'Registrar of Companies - Kolkata' },
    { code: 'IN-ROC-AHMEDABAD', name: 'Registrar of Companies - Ahmedabad' },
    { code: 'IN-ROC-PUNE', name: 'Registrar of Companies - Pune' },
    { code: 'IN-ROC-JAIPUR', name: 'Registrar of Companies - Jaipur' },
    { code: 'IN-ROC-KOCHI', name: 'Registrar of Companies - Kochi' },
    { code: 'IN-ROC-LUDHIANA', name: 'Registrar of Companies - Ludhiana' },
    { code: 'IN-ROC-GUWAHATI', name: 'Registrar of Companies - Guwahati' },
    { code: 'IN-ROC-BANGALURU', name: 'Registrar of Companies - Bangaluru' },
    { code: 'IN-ROC-HYDERABAD', name: 'Registrar of Companies - Hyderabad' },
  ],
  'ID': [{ code: 'ID-AHU', name: 'Administrasi Hukum Umum' }],
  'IR': [{ code: 'IR-TAO', name: 'Tax Administration Organization' }],
  'IQ': [{ code: 'IQ-COR', name: 'Commercial Organization Registry' }],
  'IL': [{ code: 'IL-CPA', name: 'Companies Registrar Authority' }],
  'JP': [{ code: 'JP-LRB', name: 'Legal Affairs Bureau' }],
  'JO': [{ code: 'JO-MoIC', name: 'Ministry of Industry and Trade' }],
  'KZ': [{ code: 'KZ-AR', name: 'Agency for Regulation and Development of Financial Market' }],
  'KW': [{ code: 'KW-MOCI', name: 'Ministry of Commerce and Industry' }],
  'KG': [{ code: 'KG-SSAGD', name: 'State Service on Antimonopoly Policy and Development' }],
  'LA': [{ code: 'LA-DoRC', name: 'Department of Registration and Companies' }],
  'LB': [{ code: 'LB-COR', name: 'Commercial Registry' }],
  'MO': [{ code: 'MO-RC', name: 'Registry of Companies' }],
  'MY': [{ code: 'MY-SSM', name: 'Suruhanjaya Syarikat Malaysia' }],
  'MV': [{ code: 'MV-MoLC', name: 'Ministry of Law and Gender' }],
  'MN': [{ code: 'MN-SBIC', name: 'State Business Information Center' }],
  'MM': [{ code: 'MM-DCA', name: 'Department of Company Registration' }],
  'NP': [{ code: 'NP-BR', name: 'Business Registration Office' }],
  'KP': [{ code: 'KP-MoC', name: 'Ministry of Commerce' }],
  'OM': [{{ code: 'OM-MOC', name: 'Ministry of Commerce and Industry' }],
  'PK': [{ code: 'PK-SECP', name: 'Securities and Exchange Commission of Pakistan' }],
  'PS': [{{ code: 'PS-MoNA', name: 'Ministry of National Economy' }],
  'PH': [{{ code: 'PH-SEC', name: 'Securities and Exchange Commission' }],
  'QA': [{{ code: 'QA-CR', name: 'Commercial Registry' }],
  'SA': [{{ code: 'SA-MOCI', name: 'Ministry of Commerce and Investment' }],
  'SG': [{{ code: 'SG-ACRA', name: 'Accounting and Corporate Regulatory Authority' }],
  'KR': [{{ code: 'KR-MOPF', name: 'Ministry of Planning and Finance' }],
  'LK': [{{ code: 'LK-DRC', name: 'Department of Registrar of Companies' }],
  'SY': [{{ code: 'SY-TR', name: 'Trade Registry' }],
  'TW': [{{ code: 'TW-MOEA', name: 'Ministry of Economic Affairs' }],
  'TJ': [{{ code: 'TJ-MoJ', name: 'Ministry of Justice' }],
  'TH': [{{ code: 'TH-DBD', name: 'Department of Business Development' }],
  'TL': [{{ code: 'TL-MoJ', name: 'Ministry of Justice' }],
  'TR': [{{ code: 'TR-TRA', name: 'Turkish Trade Registry' }],
  'TM': [{{ code: 'TM-SR', name: 'State Register' }],
  'AE': [{{ code: 'AE-DED', name: 'Department of Economic Development - Dubai' }],
  'UZ': [{{ code: 'UZ-MINJUST', name: 'Ministry of Justice' }],
  'VN': [{{ code: 'VN-DCA', name: 'Department of Company Registration' }],
  'YE': [{{ code: 'YE-MoC', name: 'Ministry of Commerce' }],

  // Europe
  'AX': [{ code: 'AX-PRH', name: 'Patent and Registration Office' }],
  'AT': [{ code: 'AT-FHB', name: 'Firmenbuch' }],
  'BY': [{{ code: 'BY-RECEIV', name: 'National Register of Legal Entities and Individual Entrepreneurs' }],
  'BE': [{{ code: 'BE-CBE', name: 'Crossroads Bank for Enterprises' }],
  'BA': [{{ code: 'BA-ARB', name: 'Agency for Business Registers' }],
  'BG': [{{ code: 'BG-TR', name: 'Trade Registry' }],
  'HR': [{{ code: 'HR-FINA', name: 'Financial Agency (FINA)' }],
  'CY': [{{ code: 'CY-DRC', name: 'Registrar of Companies' }],
  'CZ': [{{ code: 'CZ-CR', name: 'Commercial Register' }],
  'DK': [{{ code: 'DK-CVR', name: 'Centrale Virksomhedsregister' }],
  'EE': [{{ code: 'EE-AR', name: 'Estonian Business Register' }],
  'FI': [{{ code: 'FI-PRH', name: 'Patent and Registration Office' }],
  'FR': [
    { code: 'FR-INSEE', name: 'Institut National de la Statistique et des Études Économiques' },
    { code: 'FR-SIREN', name: 'Système d\'Identification du Répertoire des Entreprises (SIREN)' },
  ],
  'DE': [{{ code: 'DE-HRB', name: 'Handelsregister' }],
  'GR': [{{ code: 'GR-GEMI', name: 'General Electronic Commerce Registry' }],
  'HU': [{{ code: 'HU-TR', name: 'Court of Registration' }],
  'IS': [{{ code: 'IS-RS', name: 'Registers Iceland' }],
  'IE': [{{ code: 'IE-CRO', name: 'Companies Registration Office' }],
  'IT': [{{ code: 'IT-RI', name: 'Registro delle Imprese' }],
  'XK': [{{ code: 'XK-BR', name: 'Business Registry' }],
  'LV': [{{ code: 'LV-CR', name: 'Commercial Registry' }],
  'LI': [{{ code: 'LI-OHR', name: 'Obergericht - Handelsregister' }],
  'LT': [{{ code: 'LT-CR', name: 'State Enterprise Centre' }],
  'LU': [{{ code: 'LU-RCS', name: 'Registre de Commerce et des Sociétés' }],
  'MT': [{{ code: 'MT-MR', name: 'Malta Business Registry' }],
  'MD': [{{ code: 'MD-SR', name: 'State Register' }],
  'MC': [{{ code: 'MC-RCS', name: 'Registre du Commerce et des Sociétés' }],
  'ME': [{{ code: 'ME-COR', name: 'Central Registry' }],
  'NL': [{{ code: 'NL-KVK', name: 'Kamer van Koophandel' }],
  'MK': [{{ code: 'MK-CT', name: 'Central Registry' }],
  'NO': [{{ code: 'NO-BR', name: 'Business Register' }],
  'PL': [{{ code: 'PL-CR', name: 'National Court Register' }],
  'PT': [{{ code: 'PT-CRC', name: 'Conservatória de Registo Comercial' }],
  'RO': [{{ code: 'RO-ONRC', name: 'Oficiul Național de Reghistru al Comerțului' }],
  'RU': [{{ code: 'RU-EGRUL', name: 'Unified State Register of Legal Entities' }],
  'RS': [{{ code: 'RS-APR', name: 'Agency for Private Registers' }],
  'SK': [{{ code: 'SK-OR', name: 'Commercial Register' }],
  'SI': [{{ code: 'SI-SOR', name: 'Slovenian Business Register' }],
  'ES': [{{ code: 'ES-MR', name: 'Mercantile Registry' }],
  'SE': [{{ code: 'SE-BR', name: 'Business Register' }],
  'CH': [{{ code: 'CH-SHAB', name: 'Schweizerisches Handelsamtsblatt' }],
  'UA': [{{ code: 'UA-USR', name: 'Unified State Register' }],
  'GB': [{{ code: 'GB-CH', name: 'Companies House' }],

  // Additional countries with single registry
  'AL': [{{ code: 'AL-NRC', name: 'National Registration Center' }],
  'AD': [{{ code: 'AD-RPC', name: 'Registre del Comerç de Principat d\'Andorra' }],
  'KR': [{{ code: 'KR-MOPF', name: 'Ministry of Planning and Finance' }],

  // Oceania
  'AU': [{{ code: 'AU-ASIC', name: 'Australian Securities and Investments Commission' }],
  'FJ': [{{ code: 'FJ-ROC', name: 'Registrar of Companies' }],
  'KI': [{{ code: 'KI-ROC', name: 'Registrar of Companies' }],
  'MH': [{{ code: 'MH-CR', name: 'Corporate Registry' }],
  'FM': [{{ code: 'FM-CR', name: 'Corporate Registry' }],
  'NR': [{{ code: 'NR-ROC', name: 'Registrar of Companies' }],
  'NZ': [{{ code: 'NZ-COMPANIES', name: 'Companies Office' }],
  'PW': [{{ code: 'PW-CR', name: 'Corporate Registry' }],
  'PG': [{{ code: 'PG-IPA', name: 'Investment Promotion Authority' }],
  'WS': [{{ code: 'WS-RC', name: 'Registrar of Companies' }],
  'SB': [{{ code: 'SB-ROC', name: 'Registrar of Companies' }],
  'TO': [{{ code: 'TO-RC', name: 'Registrar of Companies' }],
  'TV': [{{ code: 'TV-CR', name: 'Companies Office' }],
  'VU': [{{ code: 'VU-RC', name: 'Registrar of Companies' }],
};